### ISSUE TITLE
How to install the gdal2.1.0

### ISSUE THREAD

**Issue by cploveflower** [avanetten/yolt#7]
Hi,@avanetten
When installing gdal2.1.0 with conda,why is the display:
CondaRuntimeError: Runtime error: RuntimeError: Runtime error: Could not open u'/home/cp/anaconda2/pkgs/geos-3.5.0-0.tar.bz2.part' for writing (HTTPSConnectionPool(host='repo.continuum.io', port=443): Read timed out.).

**Comment by avanetten** [comment]
Try using the Dockerfile to install gdal, rather than using conda.
